const funQuotes = [
    "💥 Why don’t scientists trust atoms? Because they make up everything!",
    "😴 I'm not lazy, I'm just on energy-saving mode.",
    "🚫 404: Motivation not found.",
    "📡 I'd tell you a UDP joke, but you might not get it.",
    "🕵️ Debugging: Being the detective in a crime movie where you are also the murderer.",
    "💸 Why did the developer go broke? Because he used up all his cache.",
    "☕ Programmer: A machine that turns coffee into code.",
    "😂 I changed my password to 'incorrect'. Now when I forget, it says: Your password is incorrect.",
    "🎯 Git commit -m 'final_final(FINAL)v9_fixed-really'",
    "👓 Why do Java devs wear glasses? Because they can’t C#.",
    "🧠 When I wrote this code, only God and I understood it. Now, only God knows.",
    "💡 There are 2 hard things in CS: cache invalidation, naming things, and off-by-one errors.",
    "🧠 My brain has too many tabs open.",
    "💡 Debugging: The art of removing bugs you didn’t know you had in ways you don’t understand.",
  "🧃 Life tip: If at first you don't succeed, call it version 1.0.",
  "🔥 Why did the developer go broke? Because he used up all his cache!",
  "🐢 I like my code how I like my turtles: slow and steady… but at least it works.",
  "🍕 You can’t make everyone happy. You’re not pizza.",
  "🦥 Procrastinators unite!... tomorrow.",
  "📦 I told my computer I needed a break… it installed updates.",
  "💻 I don't need therapy, I just need better Wi-Fi.",
  "🦄 Always code as if the person maintaining your code is a violent psychopath who knows where you live.",
  "🚀 'I'll do it later' is the first step to never doing it.",
  "🎧 I listen to podcasts to feel productive while doing absolutely nothing.",
  "👾 I came. I saw. I debugged.",
  "🧩 99 little bugs in the code, 99 little bugs. Take one down, patch it around, 127 bugs in the code!",
  "📉 Every time I fix one bug, two more rise to take its place. Hydra-code!",
  "🍀 Commit messages are just spells to make the app work.",
  "⚠️ Warning: I have no idea what I’m doing, but I’m doing it anyway.",
  "🕵️‍♂️ Stack Overflow is my co-pilot.",
  "📚 Still waiting for that ‘Real Life for Dummies’ manual.",
  "🎉 I deploy on Fridays because I love chaos!"
];

module.exports = funQuotes;
